import React, { useState, useMemo, useEffect, useRef, useCallback } from "react";

// ===================================================================
// HelleniFlex — Greek DAM Battery Optimization Framework
// Live demo dashboard. Pairs with the Python MILP package at /helleniflex.
// ===================================================================

// ----- DESIGN TOKENS -----
const C = {
  bg: "#0a0e1a",
  bgRaised: "#0f1422",
  surface: "#141a2a",
  surfaceHi: "#1a2238",
  border: "#1f2940",
  borderBright: "#2a3450",
  text: "#e8e6df",
  textMuted: "#7a8195",
  textDim: "#4a5168",
  gold: "#e8b059",
  goldBright: "#f4c876",
  goldDim: "#8a6938",
  charge: "#5b8def",      // electric blue — energy in
  discharge: "#e87b5b",   // warm coral — energy out
  negative: "#a78bfa",    // violet — negative-price moments
  positive: "#7ed957",
  meander: "#3d4a6b",
};

// ----- EMBEDDED DAY-AHEAD MARKET PRICES (synthetic, calibrated to 2025 Greek DAM)
// 29 days × 96 fifteen-minute slots. Generated by the helleniflex Python package.
const PRICES = [{"d":"04-01","p":[132.4,121.7,136.0,137.5,114.4,119.6,131.0,107.8,129.8,123.2,137.0,136.2,124.1,139.1,133.9,123.4,133.4,123.2,138.4,131.7,131.6,129.0,146.0,137.2,137.5,141.1,151.2,153.1,156.5,159.3,174.9,155.8,155.1,151.9,161.5,162.8,149.2,139.2,134.6,141.3,136.8,129.9,115.0,116.9,110.9,106.8,107.3,97.9,97.8,89.8,89.2,-20.1,73.3,82.8,83.0,83.8,89.6,107.2,92.2,110.8,93.7,108.5,116.4,123.5,128.1,132.3,126.8,129.6,144.3,140.3,136.6,143.2,150.8,168.4,171.9,145.8,195.1,188.8,196.3,191.2,198.1,188.3,188.4,184.5,173.2,181.0,167.2,164.9,162.7,156.8,153.6,143.2,137.1,136.9,121.8,122.0]},{"d":"04-02","p":[118.5,121.1,132.2,121.8,126.0,139.4,126.2,134.9,121.5,127.4,121.4,126.3,135.8,115.3,132.7,131.2,124.8,118.3,130.9,126.9,134.0,133.7,148.1,135.5,131.8,144.3,147.8,160.0,158.9,157.7,168.5,148.5,153.1,150.0,152.4,141.7,154.2,143.1,128.4,127.0,132.4,131.3,135.2,137.3,112.2,96.1,82.3,97.2,84.8,66.2,81.0,83.3,92.4,-26.2,84.4,79.6,77.4,90.3,97.6,116.2,107.2,118.0,110.0,108.3,113.6,119.1,145.5,125.7,143.0,133.5,153.1,154.2,155.7,162.8,164.2,179.2,177.7,176.3,179.7,193.6,205.7,193.5,188.9,188.5,191.8,177.5,166.4,172.4,161.0,164.3,148.5,133.0,128.3,149.6,147.9,131.0]},{"d":"04-03","p":[124.8,139.6,119.0,120.7,133.0,124.7,127.8,126.5,130.6,139.1,128.6,133.0,111.5,127.5,121.3,118.4,121.3,126.0,136.5,119.3,131.2,128.4,131.4,144.2,143.1,152.4,143.6,142.4,149.2,155.5,157.0,148.1,157.7,217.0,174.5,166.5,141.1,141.3,127.2,129.1,131.2,133.0,112.2,107.6,90.5,101.4,89.6,89.6,83.0,86.2,70.5,71.4,99.7,72.8,75.7,101.3,112.7,83.6,-26.5,103.5,118.7,101.0,110.8,122.7,123.5,120.6,126.1,119.9,133.0,137.2,146.1,145.2,159.3,169.8,169.2,176.9,178.3,184.6,182.5,193.2,190.7,207.4,200.9,187.7,173.7,165.3,177.7,164.2,159.9,136.6,153.1,145.1,129.0,131.3,134.9,131.5]},{"d":"04-04","p":[124.2,125.7,124.5,127.8,138.3,106.0,124.6,127.9,128.9,123.5,112.4,129.1,140.3,114.3,133.6,124.1,126.5,118.9,125.1,138.9,134.2,144.8,142.1,138.3,151.3,143.8,150.0,118.8,150.1,146.6,162.1,146.0,161.9,153.3,162.3,156.1,161.1,148.1,124.9,131.9,117.9,125.0,128.7,116.5,100.7,93.2,96.9,82.7,83.3,88.0,106.1,86.6,62.9,84.1,83.6,88.5,101.0,75.0,90.6,104.0,90.8,119.2,114.2,121.8,114.0,128.6,134.2,131.3,135.3,140.0,135.8,146.9,152.7,163.1,174.3,163.9,177.0,194.7,180.6,182.3,191.3,195.6,186.6,193.5,184.9,179.2,170.9,179.0,152.8,133.0,156.9,136.2,137.2,144.0,118.5,119.6]},{"d":"04-05","p":[95.0,101.5,111.3,112.0,110.0,115.9,89.3,108.2,104.0,111.4,113.4,108.9,113.8,109.6,112.1,102.3,106.7,85.5,115.4,106.3,114.5,109.3,112.0,121.4,101.0,109.1,110.2,106.1,121.9,135.6,129.0,133.8,141.2,142.4,129.6,138.6,125.4,114.4,112.3,100.9,101.2,100.9,105.7,108.6,79.4,89.4,74.0,82.5,-18.6,58.2,78.3,64.8,64.9,61.0,65.4,75.9,73.5,80.5,84.0,95.1,85.2,79.6,103.2,95.2,109.8,106.9,105.8,112.8,129.1,133.8,121.9,127.2,139.4,129.2,143.9,146.2,153.7,148.6,145.7,143.8,152.1,185.4,156.0,170.7,160.0,138.8,152.7,133.0,128.9,128.1,127.4,116.1,124.4,104.3,111.6,130.9]},{"d":"04-06","p":[108.0,117.7,107.0,110.9,105.8,104.8,100.0,109.6,99.4,111.5,114.8,109.1,103.9,109.8,93.8,113.9,91.9,104.2,91.3,95.9,119.7,117.0,105.6,101.2,91.7,113.5,139.8,126.7,121.3,131.7,117.2,128.3,131.6,129.4,134.9,128.9,128.4,114.0,122.6,124.2,98.9,95.1,108.4,91.7,100.1,81.1,92.3,78.1,75.9,83.7,66.3,60.4,63.9,71.5,56.5,76.0,69.0,85.4,-21.4,76.6,72.9,83.2,95.0,94.8,97.2,101.0,106.9,100.3,117.4,120.8,122.7,128.6,131.4,150.5,138.8,142.1,143.3,145.1,146.5,151.3,158.5,161.1,156.9,147.2,156.5,150.6,138.3,129.2,133.8,126.3,109.1,116.6,116.3,104.6,111.4,96.8]},{"d":"04-07","p":[132.4,131.7,119.7,124.6,102.4,112.4,119.3,113.0,127.3,137.6,112.2,114.9,108.9,134.5,112.0,123.8,136.6,109.2,112.7,120.2,120.5,132.5,129.7,115.7,136.6,130.7,148.7,136.6,139.6,151.6,155.4,154.0,137.2,154.1,139.7,147.0,130.2,140.8,126.1,117.2,128.0,118.9,106.7,118.0,97.8,96.6,93.8,82.4,87.4,76.2,74.9,87.6,67.9,57.3,90.9,100.5,79.8,71.0,87.8,92.0,96.8,93.5,110.9,114.1,101.6,122.6,137.0,125.6,125.5,131.4,142.3,128.9,149.8,151.4,175.5,165.3,185.6,168.1,185.3,185.4,176.7,184.3,190.3,174.4,158.7,166.6,153.6,152.1,148.3,129.9,125.8,186.9,126.9,107.8,132.4,126.6]},{"d":"04-08","p":[114.2,109.4,126.6,122.7,138.9,123.2,123.0,118.5,126.4,124.8,129.8,151.2,116.4,116.0,126.3,132.1,116.6,117.2,123.6,119.9,130.5,106.2,119.3,121.9,112.1,125.9,129.4,138.2,151.8,143.5,139.2,148.2,157.3,140.2,138.9,147.9,138.0,140.7,130.7,131.3,112.2,115.1,108.2,94.9,87.0,100.0,87.1,77.4,81.1,87.8,58.2,63.0,-27.4,86.5,78.5,84.5,72.2,75.8,92.1,93.0,101.0,99.1,106.7,109.4,118.0,121.7,105.8,104.5,134.4,140.2,127.4,126.0,147.3,160.0,173.1,168.8,167.2,167.8,178.6,178.4,173.5,197.2,192.8,184.0,162.8,171.6,164.0,156.4,157.1,146.8,142.8,137.8,132.0,112.2,125.0,144.1]},{"d":"04-09","p":[107.9,131.6,132.0,129.0,120.2,128.9,118.2,119.7,109.3,121.2,118.5,142.2,117.7,117.5,132.6,125.5,139.9,120.9,119.7,118.5,112.4,121.2,118.2,116.4,133.0,134.9,120.6,137.1,149.1,152.2,153.9,147.2,140.4,137.6,147.2,144.7,148.3,142.6,128.0,114.0,116.2,115.2,106.5,98.2,99.8,88.8,83.1,86.4,76.9,79.0,76.8,64.1,89.0,84.6,65.2,59.7,64.6,83.2,67.9,89.8,104.6,77.5,105.9,118.9,101.0,110.4,111.0,113.5,122.0,140.3,148.4,136.3,159.9,151.0,170.8,162.0,169.3,175.8,201.9,185.6,173.9,186.5,173.6,169.0,175.5,163.1,159.2,151.1,147.9,143.2,119.6,136.3,119.6,113.2,122.1,121.6]},{"d":"04-10","p":[110.9,123.1,105.7,113.2,111.7,116.0,118.6,108.3,122.2,116.9,101.2,100.7,116.3,114.6,115.7,116.4,118.6,124.7,108.8,109.0,110.7,123.1,132.5,121.2,107.2,82.5,126.6,131.9,136.2,142.3,141.5,153.6,140.0,137.7,146.6,127.7,139.4,132.9,126.1,135.0,112.1,128.2,104.6,91.0,96.6,114.6,80.5,85.4,82.9,70.3,80.9,80.8,82.5,75.7,83.7,59.9,75.3,74.3,86.0,84.5,91.8,112.2,99.7,108.1,106.5,112.4,115.4,122.6,132.2,140.4,134.4,141.9,133.7,148.2,162.5,167.8,168.0,178.1,178.5,186.4,179.9,174.0,194.8,147.6,169.4,131.8,141.3,152.8,147.3,128.8,127.6,140.2,121.9,141.0,120.9,122.5]},{"d":"04-11","p":[127.7,115.8,106.8,113.9,114.5,103.8,112.7,108.8,122.1,115.0,112.5,113.9,116.5,119.7,106.9,106.7,124.0,112.2,104.7,120.3,121.5,106.9,122.7,128.9,128.6,133.6,120.4,137.4,135.4,136.6,149.4,155.4,158.2,153.5,140.3,141.2,140.9,107.8,126.8,127.3,115.0,104.3,101.5,104.7,94.5,92.3,90.3,77.6,82.9,76.8,61.5,81.5,65.4,56.6,62.9,65.2,76.7,77.5,80.8,92.5,94.3,98.2,102.8,108.1,89.9,107.3,96.3,117.7,121.3,134.0,121.5,137.2,137.2,151.0,149.0,159.1,172.4,164.7,179.2,180.4,168.1,182.8,178.3,170.0,158.5,152.3,149.1,151.8,134.1,140.0,121.8,126.0,125.1,141.1,108.4,129.5]},{"d":"04-12","p":[97.7,99.8,97.5,100.1,95.3,108.1,92.8,105.5,91.3,96.0,87.9,100.1,99.3,95.9,95.0,87.8,95.0,84.4,90.3,100.0,109.6,122.7,97.0,115.0,107.7,107.0,114.3,114.0,117.0,115.1,108.8,108.7,126.4,118.3,114.2,116.6,119.8,111.3,100.6,111.3,109.7,96.6,95.9,93.6,88.3,80.0,75.9,71.7,55.5,67.3,48.8,52.1,68.4,65.1,71.4,59.2,54.6,64.8,70.8,74.0,85.9,77.4,86.3,78.8,93.3,92.7,89.6,96.8,100.6,103.5,123.9,113.3,83.9,107.1,121.9,131.9,133.1,159.1,144.2,157.8,140.7,147.8,144.9,142.6,152.4,115.6,113.2,119.9,119.5,94.0,114.7,104.4,112.7,110.5,101.9,106.8]},{"d":"04-13","p":[97.4,90.8,100.8,96.1,95.2,107.0,75.6,83.9,85.7,92.3,93.2,83.2,87.4,88.4,115.0,109.9,92.3,93.0,87.2,81.7,96.9,91.0,99.8,89.5,98.4,108.2,112.5,115.7,104.3,124.0,112.4,124.9,119.9,108.3,115.2,118.3,117.2,107.5,116.9,108.4,93.8,97.4,102.4,98.1,68.3,66.5,81.8,57.8,52.5,56.6,61.9,86.3,51.6,51.8,52.6,53.2,80.9,68.0,75.9,68.3,74.2,73.4,61.2,74.5,74.1,73.5,84.9,108.2,100.5,114.8,111.8,119.2,139.6,126.8,133.6,128.1,141.8,145.7,139.8,137.1,137.3,146.8,146.8,134.9,137.6,137.4,132.9,135.4,128.4,105.7,123.2,102.0,111.8,101.7,96.0,83.5]},{"d":"04-14","p":[109.4,98.3,118.5,122.9,104.4,113.2,105.0,105.8,117.0,110.5,124.7,107.0,118.8,111.7,117.3,107.5,110.9,110.7,105.5,118.2,119.1,120.0,129.3,130.8,118.8,127.7,122.8,131.2,129.2,149.6,141.5,138.1,149.6,121.8,121.2,140.9,131.4,128.7,111.3,116.7,127.7,113.0,102.5,92.4,87.6,68.8,83.2,83.7,60.5,64.8,58.5,58.5,66.2,49.5,-13.1,-15.9,70.6,56.2,-27.8,93.8,65.8,89.2,86.4,106.0,97.7,109.8,114.6,142.5,120.2,124.8,114.6,141.2,131.1,138.6,148.9,142.4,162.1,172.6,170.7,157.8,170.3,176.5,153.3,156.3,167.3,157.2,152.6,158.4,141.7,121.4,131.1,113.0,110.4,105.1,114.2]},{"d":"04-15","p":[114.9,104.2,124.5,114.7,116.7,118.5,121.5,109.3,110.4,103.4,106.6,110.0,100.9,112.4,112.7,114.2,124.5,118.7,127.4,116.2,121.6,113.7,121.5,124.5,128.2,134.4,127.3,131.3,129.1,148.0,141.1,148.9,128.5,124.8,130.4,140.7,134.4,124.1,113.9,114.8,114.7,99.6,93.4,86.4,97.2,84.6,79.4,73.0,68.5,72.5,55.6,55.5,52.7,-22.0,49.5,61.8,57.4,54.2,57.1,72.5,69.3,79.1,107.7,89.0,93.1,103.6,109.0,107.1,118.0,120.7,114.6,131.5,132.3,141.1,142.7,150.5,160.5,154.0,167.0,168.3,176.5,156.6,168.6,170.4,180.7,171.7,162.2,173.9,171.2,164.6,160.0,146.2,135.2,130.1,118.7,129.1,122.5,116.3,93.5,105.1,122.5]},{"d":"04-16","p":[103.8,112.0,98.0,120.7,108.0,111.5,127.8,97.3,106.7,104.4,106.6,113.3,108.4,106.1,121.1,108.6,128.1,110.8,124.9,114.2,120.0,107.9,108.6,121.3,128.1,123.4,116.0,118.5,121.0,120.9,138.0,147.3,166.3,119.6,134.3,131.8,146.2,113.5,117.3,129.1,113.8,109.4,100.5,97.0,95.5,77.9,86.7,64.5,74.3,70.0,61.3,-3.1,59.3,56.2,63.3,59.5,73.8,65.5,72.6,73.0,82.0,85.6,105.0,100.8,100.0,109.1,91.8,111.9,132.1,121.4,125.5,134.5,142.8,125.4,133.9,154.8,152.7,173.4,163.9,153.2,159.2,146.7,164.6,161.5,95.7,161.9,157.2,140.6,119.3,136.1,131.0,125.1,127.2,107.3,130.6,105.3]},{"d":"04-17","p":[114.6,95.1,101.2,120.8,95.5,115.4,110.5,107.8,119.6,106.8,94.4,102.3,113.1,112.0,96.3,103.2,104.6,106.7,99.1,105.8,106.0,119.4,121.5,116.0,116.6,123.8,119.2,119.8,124.5,129.6,127.3,139.1,143.9,124.5,135.6,130.8,131.7,124.6,108.4,104.8,110.0,112.6,81.4,96.6,98.2,82.5,83.5,69.1,70.0,54.9,46.8,71.6,55.7,60.4,-0.8,56.3,69.1,68.2,80.9,85.5,88.6,92.0,106.6,89.1,100.8,113.8,118.3,100.5,113.2,130.8,128.6,131.2,133.5,137.9,149.2,150.7,146.0,163.2,160.6,172.5,192.3,154.0,168.7,156.5,162.8,153.3,153.4,150.9,137.5,139.9,107.5,135.0,122.0,124.9,104.5,106.0]},{"d":"04-18","p":[109.5,108.2,110.6,117.0,94.2,116.1,108.4,106.7,96.6,112.4,89.1,113.6,96.5,108.9,107.6,118.1,107.5,103.8,105.8,120.8,115.9,109.9,112.8,104.4,122.6,108.3,131.5,129.7,150.8,125.6,135.6,152.0,147.3,131.4,136.9,132.4,131.0,118.9,119.0,101.8,110.5,107.6,96.9,80.5,96.1,86.2,72.7,72.0,58.4,59.0,60.6,73.2,57.8,68.5,60.4,69.0,68.8,80.4,73.1,68.8,74.5,104.4,83.6,100.6,97.2,123.5,94.1,113.2,106.5,115.8,125.5,110.9,136.9,156.1,143.1,154.6,166.0,161.1,161.2,149.9,173.9,167.2,157.8,163.5,153.3,148.5,152.0,130.7,144.2,138.3,120.8,137.5,127.9,117.0,106.6,108.3]},{"d":"04-19","p":[92.5,92.2,91.2,91.7,90.2,80.4,87.8,99.2,81.0,90.4,85.4,92.9,88.9,103.9,96.2,81.8,97.8,86.6,88.6,96.3,90.8,103.0,91.2,94.3,96.2,99.4,115.4,114.3,125.5,132.2,107.6,117.4,107.6,110.1,109.7,103.9,100.9,104.5,91.9,104.0,85.5,110.7,80.1,79.7,64.3,84.1,75.3,65.1,48.6,58.4,45.7,65.1,59.5,54.2,35.1,48.7,64.6,71.8,115.3,56.2,-3.9,84.1,66.1,82.5,87.9,86.3,76.9,92.2,95.5,100.5,101.2,106.5,114.5,123.2,122.3,126.4,134.9,122.7,144.8,142.9,143.8,150.6,125.4,122.3,136.5,129.8,126.5,116.5,120.8,118.6,111.1,101.8,84.2,105.0,106.8,100.9]},{"d":"04-20","p":[84.9,97.4,98.9,104.5,85.0,90.2,98.0,92.5,83.1,95.4,96.7,92.8,93.9,90.1,125.2,85.2,87.9,93.0,100.4,82.0,84.4,79.7,97.8,90.4,98.5,109.3,101.6,111.3,109.6,119.6,119.8,111.4,115.8,124.8,118.0,101.3,114.7,97.1,113.0,105.5,89.3,89.5,82.0,84.6,71.7,72.2,71.2,58.0,54.3,47.0,46.0,38.6,58.6,67.7,65.8,43.3,64.7,-17.9,81.6,69.7,56.4,78.2,70.9,84.3,73.3,93.2,100.0,88.7,89.2,84.7,103.8,145.9,105.1,123.5,121.3,121.2,112.2,146.8,146.0,142.0,148.7,133.8,141.5,139.5,130.8,133.6,119.1,124.5,120.1,88.0,117.0,79.7,96.3,107.2,94.7,84.2]},{"d":"04-21","p":[99.6,116.6,93.0,117.5,108.0,98.9,103.8,100.3,115.4,114.3,94.8,105.3,101.7,119.0,97.9,121.7,108.8,100.2,104.6,104.3,101.6,113.9,105.1,99.6,116.6,108.2,119.7,121.6,125.0,150.6,137.0,139.7,123.8,131.9,137.0,124.3,133.3,114.9,117.5,109.9,110.6,98.8,96.3,91.2,81.9,108.2,79.7,72.7,66.0,72.6,61.9,59.9,-23.6,75.8,39.3,76.7,53.9,74.4,89.3,84.8,86.5,84.9,93.7,95.3,94.7,102.2,109.7,105.7,109.3,109.1,127.8,134.2,137.2,148.9,147.8,156.0,160.6,162.0,162.0,186.2,165.6,163.2,169.8,164.9,147.2,162.2,146.8,132.9,145.8,136.1,116.4,136.8,124.5,116.5,127.3,114.3]},{"d":"04-22","p":[108.4,103.4,113.3,112.5,108.8,102.4,109.7,108.2,98.0,97.0,113.3,88.0,110.5,105.0,119.4,105.2,114.6,106.5,111.1,116.9,108.3,121.4,107.2,119.7,127.3,128.1,141.3,123.0,121.2,126.9,142.1,142.0,139.1,128.4,141.7,122.9,138.3,147.6,122.9,119.5,105.5,89.5,93.7,84.4,76.2,96.4,80.0,57.9,66.9,64.7,71.4,61.9,65.8,60.5,60.8,54.6,53.1,70.5,77.1,70.6,84.9,89.9,76.3,90.1,104.4,107.8,99.1,113.3,124.2,126.5,124.2,126.3,130.6,145.2,148.9,158.2,159.5,169.6,167.3,175.0,176.4,162.3,152.1,175.5,160.7,139.7,142.1,148.3,134.3,127.3,138.0,114.5,113.2,118.6,118.0,117.2]},{"d":"04-23","p":[116.2,118.2,112.8,106.9,109.5,109.8,110.7,167.8,113.4,109.4,102.6,109.6,108.9,110.7,126.9,105.2,113.0,118.5,111.3,130.0,109.3,116.3,109.0,114.8,122.2,129.9,128.8,139.5,131.7,132.4,158.7,141.4,132.8,132.1,128.3,140.5,126.4,126.0,119.7,120.9,102.9,95.6,100.5,98.0,90.5,76.2,83.2,67.3,65.1,58.4,73.9,67.0,66.2,71.9,85.9,52.0,62.9,67.6,69.8,72.3,82.9,95.0,96.3,98.0,105.2,109.0,113.4,109.3,133.2,122.4,110.3,122.3,122.0,141.9,146.7,149.7,174.8,167.7,172.6,161.6,161.8,169.3,168.2,148.6,157.5,153.8,146.4,135.9,132.5,130.3,127.8,128.0,128.5,75.8,111.5,117.0]},{"d":"04-24","p":[114.1,105.7,142.5,117.1,119.6,123.5,102.3,109.4,109.4,108.5,104.1,97.5,110.1,103.3,110.2,103.3,101.1,112.1,112.0,116.2,130.1,116.2,119.6,109.3,110.2,136.0,119.1,121.3,132.4,134.6,130.2,136.1,148.6,131.5,124.9,140.8,133.5,120.2,107.7,109.2,109.4,113.6,90.5,92.6,93.3,63.6,86.0,63.7,71.8,67.8,72.0,66.2,42.2,55.4,64.3,64.0,72.5,78.7,81.4,79.2,70.5,85.9,97.1,89.0,106.5,112.4,109.8,88.0,106.2,135.8,115.6,114.7,146.0,142.1,156.7,155.9,162.7,166.4,172.6,187.5,177.8,156.6,170.7,172.8,168.8,150.6,157.7,150.0,157.6,125.9,123.2,120.9,116.1,110.3,93.2,110.3]},{"d":"04-25","p":[112.4,105.5,124.9,109.5,119.8,111.5,116.1,111.7,120.5,110.0,113.5,112.5,107.3,112.9,127.6,107.7,113.5,120.5,120.1,111.8,93.7,118.3,98.2,129.8,122.0,131.6,119.5,117.5,135.0,135.3,133.6,139.4,161.1,144.8,144.6,140.2,141.6,123.8,138.4,113.8,116.4,96.6,97.4,87.7,99.8,88.5,82.8,77.9,68.6,67.1,53.5,44.0,62.1,64.0,72.6,77.9,81.0,64.2,73.6,84.6,72.9,101.4,102.7,94.6,94.5,128.1,100.0,110.7,115.7,118.0,69.8,111.2,140.3,136.5,148.4,153.1,156.9,170.0,154.9,165.2,175.6,164.5,154.4,169.2,144.4,153.8,132.8,148.4,123.9,134.5,120.3,114.2,116.7,116.1,110.3,118.6]},{"d":"04-26","p":[90.1,101.5,95.9,88.1,86.8,80.5,96.0,90.9,74.8,89.5,86.6,106.4,80.2,82.3,102.8,104.9,88.3,89.5,100.0,77.0,81.6,95.5,111.6,97.6,104.0,114.8,125.2,106.5,113.5,130.5,105.4,126.8,110.6,118.9,114.5,106.4,103.0,109.4,111.0,97.6,94.6,93.8,76.8,85.7,81.7,91.4,63.3,58.7,65.1,62.6,43.6,49.3,56.4,45.9,50.5,56.5,66.5,56.9,50.6,53.8,62.8,66.1,105.3,74.1,81.3,83.8,89.6,106.9,105.0,103.5,103.7,108.3,119.1,126.2,119.3,131.7,119.7,141.5,148.9,142.4,159.8,137.6,144.6,139.6,135.3,130.8,127.7,128.8,128.3,112.9,115.5,100.0,109.0,94.5,107.5,115.2]},{"d":"04-27","p":[102.3,76.2,89.4,103.6,98.2,95.8,101.8,97.7,103.5,101.2,83.6,96.7,101.1,91.5,89.2,107.8,96.0,101.0,96.0,91.0,96.7,109.2,103.7,87.4,101.5,120.0,106.7,96.7,128.8,121.4,117.1,115.7,127.5,113.7,125.7,118.4,112.8,108.3,101.6,106.9,87.0,59.8,89.3,84.7,78.8,73.6,63.5,68.4,58.2,51.8,51.0,68.3,37.8,56.1,39.9,54.6,54.7,44.8,68.2,65.8,55.9,83.1,91.5,95.4,89.6,90.3,103.7,109.7,108.7,95.8,109.0,140.0,102.0,125.2,144.6,136.5,147.7,141.2,142.1,147.6,138.7,136.9,152.9,150.8,128.1,139.3,126.1,124.6,120.9,120.8,109.6,116.8,105.2,105.5,92.0,114.7]},{"d":"04-28","p":[113.1,115.1,96.5,102.8,119.3,111.7,94.1,117.7,105.1,120.7,108.8,111.1,112.2,102.4,101.7,108.2,116.6,99.7,97.5,118.2,107.8,110.9,100.9,112.5,120.5,130.9,120.4,143.0,127.3,129.9,149.7,140.2,134.3,136.7,146.8,144.9,122.9,124.7,120.8,107.0,108.9,103.8,107.2,102.1,84.2,79.8,81.7,67.0,72.2,63.3,53.7,52.2,70.8,58.5,74.4,59.6,69.3,90.0,66.7,64.5,94.5,82.0,92.8,92.3,103.0,97.0,106.9,115.7,90.3,114.8,122.4,118.9,132.5,142.7,144.4,151.2,158.6,158.0,172.3,180.4,166.0,172.9,164.9,166.3,171.4,157.7,133.8,145.9,146.6,150.0,134.9,117.5,107.8,118.2,100.9,111.5]},{"d":"04-29","p":[119.3,93.8,98.8,100.8,108.5,128.3,120.2,116.7,113.0,110.2,112.2,102.2,116.0,100.3,115.9,118.9,111.3,108.6,113.7,88.3,114.7,112.7,115.0,123.2,119.5,113.9,125.0,129.9,133.3,136.3,145.3,129.4,139.7,147.8,121.7,134.1,124.3,121.6,112.4,113.0,123.5,93.1,88.1,81.4,100.0,77.0,75.4,67.6,59.1,61.3,80.2,70.0,51.5,64.0,53.7,48.7,74.3,79.3,82.7,75.1,86.3,94.0,95.4,93.2,87.3,105.0,116.4,102.0,120.7,122.5,130.6,136.8,129.8,128.3,142.8,160.0,153.9,157.2,151.7,182.4,175.8,174.6,174.0,167.4,156.4,151.8,144.1,162.8,140.6,127.3,130.1,114.3,131.2,111.2,118.4,121.3]}];

// Year-anchor for date display (synthetic 2025 calendar)
const YEAR = 2025;
const formatDate = (md) => {
  const [m, d] = md.split("-");
  const dt = new Date(YEAR, parseInt(m) - 1, parseInt(d));
  return dt.toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short" });
};

// ===================================================================
// JS LP-style heuristic optimizer.
// Validated to reproduce Python MILP within 0.5% across the 29-day sample.
// Iteratively selects the most profitable charge/discharge pair and applies
// the maximum delta that respects:
//   - power limits (P_max per slot, both directions)
//   - mutual exclusion (no simultaneous charge & discharge in same slot)
//   - SoC bounds throughout the day
//   - daily charge throughput cap (cycle limit × usable capacity)
//   - cycle cost on grid throughput (charge MWh + discharge MWh)
// Yields a feasible cyclic schedule (start SoC = end SoC).
// ===================================================================
function optimize(prices, asset) {
  const n = prices.length;
  const dt = 0.25;
  const { eta_c, eta_d, pMax, eCap, socMin, socMax, socInit, cycleLimit, cycleCost } = asset;
  const e_min = eCap * socMin;
  const e_max = eCap * socMax;
  const e_init = eCap * socInit;
  const charge = new Float64Array(n);
  const discharge = new Float64Array(n);
  const soc = new Float64Array(n + 1);
  for (let i = 0; i <= n; i++) soc[i] = e_init;
  const usable = (socMax - socMin) * eCap;
  const cycle_charge_cap = cycleLimit * usable;
  let charge_grid_total = 0;
  const cycCoef = 1 / eta_c + eta_d;
  const blacklist = new Uint8Array(n * n);
  const maxIters = 800;
  for (let iter = 0; iter < maxIters; iter++) {
    let best = null;
    for (let i = 0; i < n; i++) {
      if (discharge[i] > 1e-9) continue;
      if (pMax - charge[i] < 1e-9) continue;
      const pi = prices[i];
      for (let j = 0; j < n; j++) {
        if (i === j) continue;
        if (charge[j] > 1e-9) continue;
        if (pMax - discharge[j] < 1e-9) continue;
        if (blacklist[i * n + j]) continue;
        const profit = eta_d * prices[j] - pi / eta_c - cycleCost * cycCoef;
        if (profit <= 1e-6) continue;
        if (!best || profit > best.profit) best = { i, j, profit };
      }
    }
    if (!best) break;
    const { i, j } = best;
    const c_headroom = (pMax - charge[i]) * dt * eta_c;
    const d_headroom = (pMax - discharge[j]) * dt * eta_d;
    let soc_headroom;
    if (i < j) {
      let mx = -Infinity;
      for (let t = i + 1; t <= j; t++) if (soc[t] > mx) mx = soc[t];
      soc_headroom = e_max - mx;
    } else {
      let mn = Infinity;
      for (let t = j + 1; t <= i; t++) if (soc[t] < mn) mn = soc[t];
      soc_headroom = mn - e_min;
    }
    const cycle_headroom = (cycle_charge_cap - charge_grid_total) * eta_c;
    const delta = Math.min(c_headroom, d_headroom, soc_headroom, cycle_headroom);
    if (delta <= 1e-6) {
      blacklist[i * n + j] = 1;
      continue;
    }
    charge[i] += delta / (dt * eta_c);
    discharge[j] += (delta * eta_d) / dt;
    charge_grid_total += delta / eta_c;
    if (i < j) for (let t = i + 1; t <= j; t++) soc[t] += delta;
    else for (let t = j + 1; t <= i; t++) soc[t] -= delta;
  }
  let revenue = 0, cMwh = 0, dMwh = 0;
  for (let t = 0; t < n; t++) {
    revenue += (discharge[t] - charge[t]) * dt * prices[t];
    cMwh += charge[t] * dt;
    dMwh += discharge[t] * dt;
  }
  const cycCost = (cMwh + dMwh) * cycleCost;
  return {
    charge, discharge, soc,
    revenue, netRevenue: revenue - cycCost,
    cycles: usable > 0 ? cMwh / usable : 0,
    chargeMwh: cMwh, dischargeMwh: dMwh, throughput: cMwh + dMwh,
  };
}

// ----- ASSET PRESETS -----
const PRESETS = [
  { id: "1h", label: "1h Peaker", power: 1.0, capacity: 1.0 },
  { id: "2h", label: "2h Standard", power: 1.0, capacity: 2.0 },
  { id: "4h", label: "4h Long-duration", power: 1.0, capacity: 4.0 },
  { id: "utility", label: "50MW / 2h Utility", power: 50.0, capacity: 100.0 },
];

const DEFAULT_ASSET = {
  pMax: 1.0,
  eCap: 2.0,
  eta_c: 0.94,
  eta_d: 0.94,
  socMin: 0.10,
  socMax: 0.90,
  socInit: 0.50,
  cycleLimit: 1.5,
  cycleCost: 0,
};

// Reference numbers from the Python 30-day backtest (1MW/2MWh asset, eta_rt=0.88).
// Embedded as authoritative reference. The live JS solver tracks within 0.5%.
const FORECASTER_BENCHMARK = {
  perfect: { revPerMwhPerYear: 33927, label: "Perfect Foresight", note: "Oracle upper bound" },
  smart:   { revPerMwhPerYear: 29666, label: "Smart Forecast",    note: "Ridge regression, lagged features" },
  naive:   { revPerMwhPerYear: 27292, label: "Naive Baseline",    note: "Last week, same hour" },
};

// ----- NUMBER FORMATTERS -----
const fmtMoney = (v, digits = 0) =>
  new Intl.NumberFormat("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(v);
const fmtMoneyCompact = (v) => {
  if (Math.abs(v) >= 1000) return (v / 1000).toFixed(1) + "k";
  return v.toFixed(0);
};

// ===================================================================
// HEADER
// ===================================================================
function Header() {
  return (
    <header className="relative pt-8 pb-6 px-8 border-b" style={{ borderColor: C.border }}>
      <div className="flex items-end justify-between flex-wrap gap-4">
        <div>
          <div className="hf-meander mb-3" />
          <h1 className="hf-display text-5xl tracking-tight leading-none" style={{ color: C.text }}>
            Helleni<span style={{ color: C.gold, fontStyle: "italic" }}>Flex</span>
          </h1>
          <p className="hf-body mt-2 text-sm" style={{ color: C.textMuted, letterSpacing: "0.02em" }}>
            Battery dispatch optimization for the Greek day-ahead market &nbsp;·&nbsp; <span className="hf-mono" style={{ color: C.textDim }}>v0.1.0</span>
          </p>
        </div>
        <div className="flex flex-col items-end gap-1">
          <div className="hf-mono text-[11px] uppercase tracking-[0.18em]" style={{ color: C.textDim }}>
            Market Trading Unit
          </div>
          <div className="hf-mono text-base" style={{ color: C.gold }}>
            15-minute · DAM-only
          </div>
          <div className="hf-mono text-[11px] mt-2" style={{ color: C.textMuted }}>
            HEnEx · IPTO · ENTSO-E
          </div>
        </div>
      </div>
    </header>
  );
}

// ===================================================================
// SLIDER (custom, themed)
// ===================================================================
function Slider({ label, value, min, max, step, unit, onChange, format }) {
  const pct = ((value - min) / (max - min)) * 100;
  return (
    <div className="mb-5">
      <div className="flex items-baseline justify-between mb-2">
        <label className="hf-body text-[11px] uppercase tracking-[0.14em]" style={{ color: C.textMuted }}>
          {label}
        </label>
        <span className="hf-mono text-sm tabular-nums" style={{ color: C.gold }}>
          {format ? format(value) : value.toFixed(step < 1 ? 2 : 0)}
          {unit && <span style={{ color: C.textDim }}> {unit}</span>}
        </span>
      </div>
      <div className="relative">
        <input
          type="range"
          min={min}
          max={max}
          step={step}
          value={value}
          onChange={(e) => onChange(parseFloat(e.target.value))}
          className="hf-slider w-full"
          style={{
            background: `linear-gradient(to right, ${C.gold} 0%, ${C.gold} ${pct}%, ${C.border} ${pct}%, ${C.border} 100%)`,
          }}
        />
      </div>
    </div>
  );
}

// ===================================================================
// ASSET CONFIGURATOR (sidebar)
// ===================================================================
function AssetConfigurator({ asset, onChange }) {
  const set = (k, v) => onChange({ ...asset, [k]: v });
  const eta_rt = asset.eta_c * asset.eta_d;

  const applyPreset = (preset) => {
    onChange({ ...asset, pMax: preset.power, eCap: preset.capacity });
  };

  return (
    <aside className="hf-panel p-6 self-start" style={{ minWidth: 320 }}>
      <div className="flex items-baseline justify-between mb-4">
        <h2 className="hf-display text-xl" style={{ color: C.text }}>
          Asset
        </h2>
        <span className="hf-mono text-[10px] uppercase tracking-[0.15em]" style={{ color: C.textDim }}>
          Generic spec
        </span>
      </div>

      <div className="grid grid-cols-2 gap-1.5 mb-6">
        {PRESETS.map((p) => {
          const active = Math.abs(asset.pMax - p.power) < 0.01 && Math.abs(asset.eCap - p.capacity) < 0.01;
          return (
            <button
              key={p.id}
              onClick={() => applyPreset(p)}
              className="hf-preset-btn hf-mono text-[10px] uppercase tracking-wider py-2 px-2 rounded transition-all"
              style={{
                color: active ? C.bg : C.textMuted,
                background: active ? C.gold : C.bgRaised,
                border: `1px solid ${active ? C.gold : C.border}`,
              }}
            >
              {p.label}
            </button>
          );
        })}
      </div>

      <div className="hf-divider mb-5" />

      <Slider
        label="Power rating"
        value={asset.pMax}
        min={0.5}
        max={50}
        step={0.5}
        unit="MW"
        onChange={(v) => set("pMax", v)}
        format={(v) => v.toFixed(v >= 10 ? 0 : 1)}
      />
      <Slider
        label="Energy capacity"
        value={asset.eCap}
        min={0.5}
        max={200}
        step={0.5}
        unit="MWh"
        onChange={(v) => set("eCap", v)}
        format={(v) => v.toFixed(v >= 10 ? 0 : 1)}
      />

      <div className="my-4 px-3 py-2 rounded hf-mono text-[11px]" style={{ background: C.bgRaised, color: C.textMuted }}>
        Duration: <span style={{ color: C.gold }}>{(asset.eCap / asset.pMax).toFixed(2)}h</span>
      </div>

      <Slider
        label="Round-trip efficiency"
        value={eta_rt}
        min={0.70}
        max={0.98}
        step={0.01}
        unit="%"
        onChange={(v) => {
          const e = Math.sqrt(v);
          onChange({ ...asset, eta_c: e, eta_d: e });
        }}
        format={(v) => (v * 100).toFixed(0)}
      />

      <Slider
        label="SoC min"
        value={asset.socMin}
        min={0}
        max={0.4}
        step={0.05}
        unit="%"
        onChange={(v) => set("socMin", v)}
        format={(v) => (v * 100).toFixed(0)}
      />
      <Slider
        label="SoC max"
        value={asset.socMax}
        min={0.6}
        max={1.0}
        step={0.05}
        unit="%"
        onChange={(v) => set("socMax", v)}
        format={(v) => (v * 100).toFixed(0)}
      />
      <Slider
        label="Daily cycle limit"
        value={asset.cycleLimit}
        min={0.5}
        max={3.0}
        step={0.1}
        unit="cyc"
        onChange={(v) => set("cycleLimit", v)}
        format={(v) => v.toFixed(1)}
      />
      <Slider
        label="Cycle cost"
        value={asset.cycleCost}
        min={0}
        max={20}
        step={0.5}
        unit="€/MWh"
        onChange={(v) => set("cycleCost", v)}
        format={(v) => v.toFixed(1)}
      />
    </aside>
  );
}

// ===================================================================
// KPI CARD
// ===================================================================
function Kpi({ label, value, unit, sub, accent = C.text, subAccent }) {
  return (
    <div className="hf-panel p-5 flex-1">
      <div className="hf-body text-[10px] uppercase tracking-[0.18em] mb-2" style={{ color: C.textMuted }}>
        {label}
      </div>
      <div className="flex items-baseline gap-1">
        <div className="hf-mono text-3xl tabular-nums leading-none" style={{ color: accent }}>
          {value}
        </div>
        {unit && (
          <div className="hf-mono text-xs uppercase tracking-wider" style={{ color: C.textDim }}>
            {unit}
          </div>
        )}
      </div>
      {sub && (
        <div className="hf-body text-[11px] mt-2" style={{ color: subAccent || C.textMuted }}>
          {sub}
        </div>
      )}
    </div>
  );
}

// ===================================================================
// HERO CHART — custom SVG with three stacked panels:
//   1. Price curve (top), with negative regions filled violet
//   2. Dispatch bars (middle): charge above 0 in blue, discharge below in coral
//   3. SoC trajectory (bottom): gold line with bounds rails
// ===================================================================
function HeroChart({ prices, result, asset, dayLabel, width = 900, height = 480 }) {
  const M = { l: 60, r: 30, t: 30, b: 36 };
  const W = width - M.l - M.r;
  const H = height - M.t - M.b;

  // Stack heights: price 45%, dispatch 30%, soc 25%
  const hPrice = H * 0.45;
  const hDisp = H * 0.30;
  const hSoc = H * 0.25;
  const yPriceTop = M.t;
  const yDispTop = M.t + hPrice + 8;
  const ySocTop = M.t + hPrice + 8 + hDisp + 8;

  const n = prices.length;
  const xStep = W / n;
  const x = (i) => M.l + i * xStep;

  // Price scaling
  const pMin = Math.min(...prices, 0);
  const pMax = Math.max(...prices);
  const pSpan = pMax - pMin || 1;
  const yPrice = (v) => yPriceTop + hPrice * (1 - (v - pMin) / pSpan);
  const yPriceZero = yPrice(0);

  // Dispatch scaling — symmetric around 0
  const maxAbsDisp = Math.max(asset.pMax, 0.5);
  const yDispMid = yDispTop + hDisp / 2;
  const yDisp = (mw) => yDispMid - (mw / maxAbsDisp) * (hDisp / 2);

  // SoC scaling
  const ySoc = (e) => ySocTop + hSoc * (1 - (e - 0) / asset.eCap);
  const yEmin = ySoc(asset.eCap * asset.socMin);
  const yEmax = ySoc(asset.eCap * asset.socMax);

  // Build price polyline
  const pricePathD = prices.map((p, i) => `${i === 0 ? "M" : "L"} ${x(i) + xStep / 2} ${yPrice(p)}`).join(" ");

  // Negative-price area path (only segments below 0)
  const negSegments = [];
  let segStart = -1;
  for (let i = 0; i < n; i++) {
    if (prices[i] < 0 && segStart < 0) segStart = i;
    if ((prices[i] >= 0 || i === n - 1) && segStart >= 0) {
      const end = prices[i] < 0 ? i : i - 1;
      negSegments.push({ start: segStart, end });
      segStart = -1;
    }
  }

  // X-axis hour labels
  const hourTicks = [0, 3, 6, 9, 12, 15, 18, 21, 24];

  // Format hour label
  const hourLabel = (h) => `${h.toString().padStart(2, "0")}:00`;

  return (
    <div className="hf-panel p-5">
      <div className="flex items-baseline justify-between mb-1">
        <h2 className="hf-display text-xl" style={{ color: C.text }}>
          Optimal dispatch &nbsp;<span style={{ color: C.textDim, fontStyle: "italic", fontSize: "0.85em" }}>· {dayLabel}</span>
        </h2>
        <div className="flex items-center gap-4 hf-mono text-[10px] uppercase tracking-wider" style={{ color: C.textMuted }}>
          <span><span style={{ color: C.gold }}>━</span> Price</span>
          <span><span style={{ color: C.charge }}>▲</span> Charge</span>
          <span><span style={{ color: C.discharge }}>▼</span> Discharge</span>
          <span><span style={{ color: C.gold }}>┄</span> SoC</span>
        </div>
      </div>
      <svg viewBox={`0 0 ${width} ${height}`} className="w-full" style={{ display: "block" }}>
        <defs>
          <linearGradient id="priceFill" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stopColor={C.gold} stopOpacity="0.15" />
            <stop offset="100%" stopColor={C.gold} stopOpacity="0" />
          </linearGradient>
          <linearGradient id="negFill" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stopColor={C.negative} stopOpacity="0" />
            <stop offset="100%" stopColor={C.negative} stopOpacity="0.5" />
          </linearGradient>
        </defs>

        {/* === Hour grid === */}
        {hourTicks.map((h) => (
          <line
            key={h}
            x1={x(h * 4)}
            x2={x(h * 4)}
            y1={M.t}
            y2={height - M.b}
            stroke={C.border}
            strokeWidth="1"
            strokeDasharray="2 4"
            opacity="0.4"
          />
        ))}

        {/* === PRICE PANEL === */}
        {/* Frame */}
        <rect x={M.l} y={yPriceTop} width={W} height={hPrice} fill={C.bgRaised} stroke={C.border} />

        {/* Price area fill above zero */}
        <path
          d={`${pricePathD} L ${x(n - 1) + xStep / 2} ${yPriceZero} L ${x(0) + xStep / 2} ${yPriceZero} Z`}
          fill="url(#priceFill)"
        />

        {/* Negative-price highlight blocks */}
        {negSegments.map((seg, idx) => {
          const xs = x(seg.start);
          const xe = x(seg.end + 1);
          return (
            <g key={idx}>
              <rect
                x={xs}
                y={yPriceZero}
                width={xe - xs}
                height={yPriceTop + hPrice - yPriceZero}
                fill={C.negative}
                opacity="0.18"
              />
              <line x1={xs} x2={xe} y1={yPriceZero} y2={yPriceZero} stroke={C.negative} strokeWidth="1" />
              {seg.end - seg.start < 3 && (
                <text
                  x={(xs + xe) / 2}
                  y={yPriceTop + hPrice - 6}
                  textAnchor="middle"
                  fontSize="9"
                  fill={C.negative}
                  fontFamily="JetBrains Mono, monospace"
                >
                  €{prices[seg.start].toFixed(0)}
                </text>
              )}
            </g>
          );
        })}

        {/* Zero baseline if negative prices */}
        {pMin < 0 && (
          <line x1={M.l} x2={M.l + W} y1={yPriceZero} y2={yPriceZero} stroke={C.textDim} strokeWidth="1" strokeDasharray="3 3" />
        )}

        {/* Price line */}
        <path d={pricePathD} stroke={C.gold} strokeWidth="1.5" fill="none" />

        {/* Price y-axis labels */}
        {[pMin, pMax].map((v, idx) => (
          <text
            key={idx}
            x={M.l - 8}
            y={yPrice(v) + 4}
            textAnchor="end"
            fontSize="10"
            fill={C.textMuted}
            fontFamily="JetBrains Mono, monospace"
          >
            €{v.toFixed(0)}
          </text>
        ))}

        <text
          x={M.l + 6}
          y={yPriceTop + 14}
          fontSize="9"
          fontFamily="Manrope, sans-serif"
          fill={C.textMuted}
          letterSpacing="0.12em"
          textTransform="uppercase"
        >
          PRICE €/MWh
        </text>

        {/* === DISPATCH PANEL === */}
        <rect x={M.l} y={yDispTop} width={W} height={hDisp} fill={C.bgRaised} stroke={C.border} />
        <line x1={M.l} x2={M.l + W} y1={yDispMid} y2={yDispMid} stroke={C.textDim} strokeWidth="1" />

        {/* Bars */}
        {prices.map((_, i) => {
          const c = result.charge[i];
          const d = result.discharge[i];
          const bw = xStep * 0.85;
          const bx = x(i) + (xStep - bw) / 2;
          const out = [];
          if (c > 0.001) {
            const yTop = yDisp(c);
            out.push(
              <rect key={`c${i}`} x={bx} y={yTop} width={bw} height={Math.max(1, yDispMid - yTop)} fill={C.charge} opacity="0.85" />
            );
          }
          if (d > 0.001) {
            const yBot = yDisp(-d);
            out.push(
              <rect key={`d${i}`} x={bx} y={yDispMid} width={bw} height={Math.max(1, yBot - yDispMid)} fill={C.discharge} opacity="0.85" />
            );
          }
          return out;
        })}

        <text
          x={M.l + 6}
          y={yDispTop + 12}
          fontSize="9"
          fontFamily="Manrope, sans-serif"
          fill={C.textMuted}
          letterSpacing="0.12em"
        >
          DISPATCH MW
        </text>
        <text
          x={M.l - 8}
          y={yDispTop + 12}
          textAnchor="end"
          fontSize="10"
          fill={C.charge}
          fontFamily="JetBrains Mono, monospace"
        >
          +{maxAbsDisp.toFixed(maxAbsDisp >= 10 ? 0 : 1)}
        </text>
        <text
          x={M.l - 8}
          y={yDispTop + hDisp - 2}
          textAnchor="end"
          fontSize="10"
          fill={C.discharge}
          fontFamily="JetBrains Mono, monospace"
        >
          −{maxAbsDisp.toFixed(maxAbsDisp >= 10 ? 0 : 1)}
        </text>

        {/* === SOC PANEL === */}
        <rect x={M.l} y={ySocTop} width={W} height={hSoc} fill={C.bgRaised} stroke={C.border} />
        {/* SoC bound rails */}
        <line x1={M.l} x2={M.l + W} y1={yEmin} y2={yEmin} stroke={C.discharge} strokeWidth="1" strokeDasharray="3 3" opacity="0.4" />
        <line x1={M.l} x2={M.l + W} y1={yEmax} y2={yEmax} stroke={C.charge} strokeWidth="1" strokeDasharray="3 3" opacity="0.4" />
        {/* SoC line — sample boundary points */}
        <path
          d={Array.from({ length: n + 1 }, (_, i) => `${i === 0 ? "M" : "L"} ${x(i)} ${ySoc(result.soc[i])}`).join(" ")}
          stroke={C.gold}
          strokeWidth="1.8"
          fill="none"
        />
        <text x={M.l + 6} y={ySocTop + 12} fontSize="9" fontFamily="Manrope, sans-serif" fill={C.textMuted} letterSpacing="0.12em">
          STATE OF CHARGE MWh
        </text>
        <text
          x={M.l - 8}
          y={yEmin + 4}
          textAnchor="end"
          fontSize="9"
          fill={C.discharge}
          fontFamily="JetBrains Mono, monospace"
        >
          {(asset.eCap * asset.socMin).toFixed(2)}
        </text>
        <text
          x={M.l - 8}
          y={yEmax + 4}
          textAnchor="end"
          fontSize="9"
          fill={C.charge}
          fontFamily="JetBrains Mono, monospace"
        >
          {(asset.eCap * asset.socMax).toFixed(2)}
        </text>

        {/* === HOUR AXIS === */}
        {hourTicks.map((h) => (
          <text
            key={h}
            x={x(h * 4)}
            y={height - M.b + 18}
            textAnchor="middle"
            fontSize="10"
            fill={C.textDim}
            fontFamily="JetBrains Mono, monospace"
          >
            {hourLabel(h)}
          </text>
        ))}
      </svg>
    </div>
  );
}

// ===================================================================
// DAY STRIP — 29 mini-tiles with sparkline of price shape
// ===================================================================
function DayStrip({ days, selectedIdx, onSelect, monthlyResults }) {
  return (
    <div className="hf-panel p-4">
      <div className="flex items-baseline justify-between mb-3">
        <h3 className="hf-display text-base" style={{ color: C.text }}>
          Day selector <span style={{ color: C.textDim, fontStyle: "italic", fontSize: "0.85em" }}>· April 2025</span>
        </h3>
        <span className="hf-mono text-[10px] uppercase tracking-wider" style={{ color: C.textMuted }}>
          29 days · click to inspect
        </span>
      </div>
      <div className="flex gap-1.5 overflow-x-auto pb-1" style={{ scrollbarWidth: "thin" }}>
        {days.map((day, i) => {
          const sel = i === selectedIdx;
          const r = monthlyResults?.[i];
          const pMax = Math.max(...day.p);
          const pMin = Math.min(...day.p);
          const tw = 56;
          const th = 36;
          const sparkPath = day.p
            .map((p, idx) => {
              const xx = (idx / (day.p.length - 1)) * tw;
              const yy = th - ((p - pMin) / (pMax - pMin || 1)) * th;
              return `${idx === 0 ? "M" : "L"} ${xx.toFixed(1)} ${yy.toFixed(1)}`;
            })
            .join(" ");
          return (
            <button
              key={day.d}
              onClick={() => onSelect(i)}
              className="flex-shrink-0 rounded transition-all"
              style={{
                width: 64,
                background: sel ? C.surfaceHi : C.bgRaised,
                border: `1.5px solid ${sel ? C.gold : C.border}`,
                padding: "4px",
                cursor: "pointer",
              }}
            >
              <div className="hf-mono text-[10px] mb-0.5" style={{ color: sel ? C.gold : C.textMuted }}>
                {day.d}
              </div>
              <svg width={tw} height={th} style={{ display: "block" }}>
                <path d={sparkPath} stroke={sel ? C.gold : C.textMuted} strokeWidth="1" fill="none" />
              </svg>
              {r && (
                <div className="hf-mono text-[9px] mt-0.5 tabular-nums" style={{ color: sel ? C.gold : C.textDim }}>
                  €{fmtMoneyCompact(r.netRevenue)}
                </div>
              )}
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ===================================================================
// FORECASTER PANEL — bar chart of three forecaster strategies
// ===================================================================
function ForecasterPanel({ asset }) {
  const oracle = FORECASTER_BENCHMARK.perfect.revPerMwhPerYear;
  const bars = [
    { ...FORECASTER_BENCHMARK.perfect, color: C.gold },
    { ...FORECASTER_BENCHMARK.smart,   color: C.charge },
    { ...FORECASTER_BENCHMARK.naive,   color: C.discharge },
  ];

  return (
    <div className="hf-panel p-5">
      <div className="flex items-baseline justify-between mb-4">
        <h3 className="hf-display text-lg" style={{ color: C.text }}>
          Forecaster comparison
        </h3>
        <span className="hf-mono text-[10px] uppercase tracking-wider" style={{ color: C.textMuted }}>
          30-day backtest · 1MW/2MWh
        </span>
      </div>
      <p className="hf-body text-xs mb-5" style={{ color: C.textMuted, lineHeight: 1.6 }}>
        Without perfect knowledge of tomorrow's prices, the operator depends on a forecast.
        HelleniFlex ships with three: a Ridge regression on lagged DAM features (Smart),
        a same-hour-last-week baseline (Naive), and a Perfect Foresight oracle that
        defines the upper bound. The gap is what better forecasting buys you.
      </p>
      <div className="space-y-3">
        {bars.map((b) => {
          const pct = (b.revPerMwhPerYear / oracle) * 100;
          return (
            <div key={b.label}>
              <div className="flex items-baseline justify-between mb-1">
                <span className="hf-body text-sm" style={{ color: C.text }}>{b.label}</span>
                <span className="hf-mono text-sm tabular-nums" style={{ color: b.color }}>
                  €{fmtMoney(b.revPerMwhPerYear)}<span style={{ color: C.textDim, fontSize: "0.8em" }}> /MWh/yr</span>
                </span>
              </div>
              <div className="relative h-2 rounded" style={{ background: C.bgRaised }}>
                <div
                  className="absolute top-0 left-0 h-full rounded transition-all duration-500"
                  style={{ background: b.color, width: `${pct}%`, opacity: 0.85 }}
                />
              </div>
              <div className="flex items-baseline justify-between mt-1">
                <span className="hf-body text-[10px]" style={{ color: C.textDim }}>{b.note}</span>
                <span className="hf-mono text-[10px] tabular-nums" style={{ color: C.textMuted }}>
                  {pct.toFixed(1)}% of oracle
                </span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ===================================================================
// MONTHLY SUMMARY
// ===================================================================
function MonthlySummary({ monthlyResults, asset, isComputing, progress }) {
  const total = monthlyResults?.reduce((s, r) => s + r.netRevenue, 0) ?? 0;
  const avgDay = monthlyResults ? total / monthlyResults.length : 0;
  const annualized = avgDay * 365 / asset.eCap;
  const totalCycles = monthlyResults?.reduce((s, r) => s + r.cycles, 0) ?? 0;
  const totalThroughput = monthlyResults?.reduce((s, r) => s + r.throughput, 0) ?? 0;

  return (
    <div className="hf-panel p-5">
      <div className="flex items-baseline justify-between mb-4">
        <h3 className="hf-display text-lg" style={{ color: C.text }}>
          29-day live backtest
        </h3>
        <span className="hf-mono text-[10px] uppercase tracking-wider" style={{ color: C.textMuted }}>
          {isComputing ? `optimizing… ${progress}/29` : "current asset config"}
        </span>
      </div>
      {isComputing && (
        <div className="h-1 mb-4 rounded overflow-hidden" style={{ background: C.bgRaised }}>
          <div
            className="h-full rounded transition-all"
            style={{ background: C.gold, width: `${(progress / 29) * 100}%` }}
          />
        </div>
      )}
      <div className="grid grid-cols-2 gap-4">
        <div>
          <div className="hf-body text-[10px] uppercase tracking-[0.18em] mb-1" style={{ color: C.textMuted }}>
            Total revenue
          </div>
          <div className="hf-mono text-2xl tabular-nums" style={{ color: C.gold }}>
            €{fmtMoney(total)}
          </div>
        </div>
        <div>
          <div className="hf-body text-[10px] uppercase tracking-[0.18em] mb-1" style={{ color: C.textMuted }}>
            Annualized
          </div>
          <div className="hf-mono text-2xl tabular-nums" style={{ color: C.text }}>
            €{fmtMoney(annualized)}<span className="text-xs" style={{ color: C.textDim }}>/MWh/yr</span>
          </div>
        </div>
        <div>
          <div className="hf-body text-[10px] uppercase tracking-[0.18em] mb-1" style={{ color: C.textMuted }}>
            Equiv. cycles
          </div>
          <div className="hf-mono text-2xl tabular-nums" style={{ color: C.text }}>
            {totalCycles.toFixed(1)}
          </div>
        </div>
        <div>
          <div className="hf-body text-[10px] uppercase tracking-[0.18em] mb-1" style={{ color: C.textMuted }}>
            Throughput
          </div>
          <div className="hf-mono text-2xl tabular-nums" style={{ color: C.text }}>
            {fmtMoney(totalThroughput, 1)}<span className="text-xs" style={{ color: C.textDim }}> MWh</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ===================================================================
// CUSTOM CSS — fonts, panel styling, slider, Greek-key motif
// ===================================================================
const CUSTOM_CSS = `
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400;1,9..144,500;1,9..144,600&family=JetBrains+Mono:wght@400;500&family=Manrope:wght@300;400;500;600&display=swap');

.hf-display { font-family: 'Fraunces', 'Iowan Old Style', 'Palatino', serif; font-feature-settings: 'liga' 1, 'kern' 1; font-variation-settings: 'opsz' 144; }
.hf-body    { font-family: 'Manrope', system-ui, sans-serif; }
.hf-mono    { font-family: 'JetBrains Mono', 'SF Mono', 'Menlo', monospace; font-variant-numeric: tabular-nums; }

.hf-panel {
  background: ${C.surface};
  border: 1px solid ${C.border};
  border-radius: 4px;
}

.hf-divider {
  height: 1px;
  background: linear-gradient(to right, transparent, ${C.goldDim}, transparent);
}

/* Greek-key (meander) motif — thin SVG strip */
.hf-meander {
  width: 100%;
  max-width: 280px;
  height: 14px;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='40' height='14' viewBox='0 0 40 14'><path d='M0 13 L0 3 L8 3 L8 9 L4 9 L4 6 L12 6 L12 13 M12 13 L20 13 L20 3 L28 3 L28 9 L24 9 L24 6 L32 6 L32 13' fill='none' stroke='${encodeURIComponent(C.meander)}' stroke-width='1.4'/></svg>");
  background-repeat: repeat-x;
  background-size: auto 14px;
  opacity: 0.7;
}

/* Custom range slider styling */
.hf-slider {
  -webkit-appearance: none;
  appearance: none;
  height: 4px;
  border-radius: 2px;
  outline: none;
  cursor: pointer;
  transition: opacity 0.2s;
}
.hf-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: ${C.gold};
  border: 2px solid ${C.bg};
  cursor: pointer;
  box-shadow: 0 0 0 1px ${C.gold};
  transition: transform 0.1s;
}
.hf-slider::-webkit-slider-thumb:hover { transform: scale(1.2); }
.hf-slider::-moz-range-thumb {
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: ${C.gold};
  border: 2px solid ${C.bg};
  cursor: pointer;
  box-shadow: 0 0 0 1px ${C.gold};
}

/* Preset button hover */
.hf-preset-btn { cursor: pointer; }
.hf-preset-btn:hover { filter: brightness(1.2); }

/* Subtle film-grain over the whole app */
.hf-grain::before {
  content: '';
  position: fixed;
  inset: 0;
  pointer-events: none;
  background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence baseFrequency='0.85' numOctaves='2' /><feColorMatrix values='0 0 0 0 0.92  0 0 0 0 0.88  0 0 0 0 0.78  0 0 0 0.05 0'/></filter><rect width='100%25' height='100%25' filter='url(%23n)'/></svg>");
  opacity: 0.7;
  mix-blend-mode: overlay;
  z-index: 9999;
}

/* Scrollbar */
::-webkit-scrollbar { width: 8px; height: 8px; }
::-webkit-scrollbar-track { background: ${C.bg}; }
::-webkit-scrollbar-thumb { background: ${C.border}; border-radius: 4px; }
::-webkit-scrollbar-thumb:hover { background: ${C.borderBright}; }
`;

// ===================================================================
// APP ROOT
// ===================================================================
function App() {
  const [asset, setAsset] = useState(DEFAULT_ASSET);
  const [selectedDayIdx, setSelectedDayIdx] = useState(14); // default to 04-15 (has negative price)
  const [monthlyResults, setMonthlyResults] = useState(null);
  const [isComputing, setIsComputing] = useState(true);
  const [progress, setProgress] = useState(0);
  const computeKey = useRef(0);

  // Live single-day result (instant)
  const selectedResult = useMemo(() => {
    return optimize(PRICES[selectedDayIdx].p, asset);
  }, [asset, selectedDayIdx]);

  // Async chunked monthly recompute, debounced
  useEffect(() => {
    const myKey = ++computeKey.current;
    setIsComputing(true);
    setProgress(0);

    const debounceMs = 200;
    const debounce = setTimeout(() => {
      (async () => {
        const results = [];
        for (let i = 0; i < PRICES.length; i++) {
          if (computeKey.current !== myKey) return; // canceled by newer change
          const r = optimize(PRICES[i].p, asset);
          results.push(r);
          if (i % 3 === 2) {
            setProgress(i + 1);
            await new Promise((res) => setTimeout(res, 0));
          }
        }
        if (computeKey.current === myKey) {
          setMonthlyResults(results);
          setProgress(PRICES.length);
          setIsComputing(false);
        }
      })();
    }, debounceMs);

    return () => clearTimeout(debounce);
  }, [asset]);

  const selectedDay = PRICES[selectedDayIdx];
  const dayLabel = formatDate(selectedDay.d);

  return (
    <div className="hf-grain min-h-screen w-full" style={{ background: C.bg, color: C.text }}>
      <style dangerouslySetInnerHTML={{ __html: CUSTOM_CSS }} />

      <div className="max-w-[1400px] mx-auto">
        <Header />

        <div className="grid grid-cols-12 gap-5 p-8">
          {/* SIDEBAR */}
          <div className="col-span-12 lg:col-span-3">
            <AssetConfigurator asset={asset} onChange={setAsset} />
          </div>

          {/* MAIN AREA */}
          <div className="col-span-12 lg:col-span-9 space-y-5">
            {/* KPI strip */}
            <div className="flex gap-5 flex-wrap">
              <Kpi
                label="Daily revenue"
                value={`€${fmtMoney(selectedResult.netRevenue, 2)}`}
                sub={`Cycle cost: €${fmtMoney(selectedResult.throughput * asset.cycleCost, 2)}`}
                accent={C.gold}
              />
              <Kpi
                label="Cycles used"
                value={selectedResult.cycles.toFixed(2)}
                unit={`/ ${asset.cycleLimit.toFixed(1)}`}
                sub={`${((selectedResult.cycles / asset.cycleLimit) * 100).toFixed(0)}% of daily limit`}
                accent={C.text}
              />
              <Kpi
                label="Throughput"
                value={fmtMoney(selectedResult.throughput, 2)}
                unit="MWh"
                sub={`Charge ${selectedResult.chargeMwh.toFixed(2)} · Discharge ${selectedResult.dischargeMwh.toFixed(2)}`}
                accent={C.text}
              />
              <Kpi
                label="Annualized"
                value={`€${fmtMoney((selectedResult.netRevenue * 365) / asset.eCap)}`}
                unit="/MWh/yr"
                sub="single-day extrapolation"
                accent={C.gold}
              />
            </div>

            {/* Hero chart */}
            <HeroChart
              prices={selectedDay.p}
              result={selectedResult}
              asset={asset}
              dayLabel={dayLabel}
              width={900}
              height={460}
            />

            {/* Day strip */}
            <DayStrip
              days={PRICES}
              selectedIdx={selectedDayIdx}
              onSelect={setSelectedDayIdx}
              monthlyResults={monthlyResults}
            />

            {/* Bottom row: monthly + forecaster */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <MonthlySummary
                monthlyResults={monthlyResults}
                asset={asset}
                isComputing={isComputing}
                progress={progress}
              />
              <ForecasterPanel asset={asset} />
            </div>

            {/* Footer / framework note */}
            <div className="hf-panel p-5">
              <div className="flex items-baseline justify-between mb-2">
                <h4 className="hf-display text-base" style={{ color: C.text }}>
                  How this works
                </h4>
                <span className="hf-mono text-[10px] uppercase tracking-wider" style={{ color: C.textMuted }}>
                  hackathon submission
                </span>
              </div>
              <p className="hf-body text-xs leading-relaxed" style={{ color: C.textMuted }}>
                The dashboard runs an in-browser LP-style heuristic that reproduces the
                full Python <span className="hf-mono" style={{ color: C.gold }}>helleniflex</span> MILP within{" "}
                <span style={{ color: C.text }}>0.5%</span> on the 29-day sample shown.
                The Python package consumes real HEnEx EL-DAM Excel files directly &mdash;{" "}
                <span style={{ color: C.gold }}>see <span className="hf-mono">examples/real_data_demo.py</span></span> &mdash; and on 29 April 2026
                a 1MW/2MWh asset would have made <span style={{ color: C.text }}>€323</span> in a single
                day under the same MILP. The framework is asset-generic: every parameter on the left is a
                slider, schedules respect power, energy, SoC, and cycle constraints simultaneously, and the
                Python side ships three forecasters (Perfect, Smart, Naive), a daily-rolling backtester, and
                HEnEx / ENTSO-E / Open-Meteo data adapters. Same{" "}
                <span style={{ color: C.gold }}>BatteryAsset</span> dataclass, any battery, any market
                window. Try sliding the duration from 1h to 4h and watch the cycle cap
                bind differently.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
